
package SyntaxTree;

import generated.LenguajeLexer;
import generated.LenguajeParser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import org.antlr.v4.gui.TreeViewer;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
/**
 *
 * @author carlos
 */
public class SyntaxTreePane extends javax.swing.JPanel {
    
    /**
     * Creates new form SyntaxTreePane
     */
    private JLabel titulo; 
    public SyntaxTreePane() {
        initComponents();
        configurarUI();
    }
    
    private void configurarUI() {
        // Use BorderLayout like your other panels
        setLayout(new BorderLayout(0, 0));
        setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

        setBackground(new Color(41, 49, 52));
        setOpaque(true);

        titulo = new JLabel("Árbol Sintáctico");
        titulo.setFont(new Font("Segoe UI", Font.PLAIN, 36));
        titulo.setHorizontalAlignment(SwingConstants.CENTER);
        titulo.setForeground(Color.WHITE);
        titulo.setOpaque(false);

        add(titulo, BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void showTreeGui(String codigo) {
        CharStream input = CharStreams.fromString(codigo);
        LenguajeLexer lexer = new LenguajeLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        LenguajeParser parser = new LenguajeParser(tokens);

        ParseTree tree = parser.programa();

        this.removeAll();
        this.setLayout(new BorderLayout(0, 0));
        this.setBackground(new Color(41, 49, 52));
        this.setOpaque(true);

        if (titulo == null) {
            titulo = new JLabel("Árbol Sintáctico");
            titulo.setFont(new Font("Segoe UI", 0, 36));
            Color titleColor = new Color(220, 209, 185);
            titulo.setForeground(titleColor);
            titulo.setHorizontalAlignment(SwingConstants.CENTER);
            titulo.setOpaque(false);
        }
        this.add(titulo, BorderLayout.NORTH);

        TreeViewer viewer = new TreeViewer(Arrays.asList(parser.getRuleNames()), tree);
        viewer.setScale(1.2);
        viewer.setFont(new Font("Segoe UI", Font.PLAIN, 10));
        viewer.setTextColor(Color.WHITE);

        viewer.setBackground(new Color(41, 49, 52));
        viewer.setOpaque(true);

        JScrollPane scrollPane = new JScrollPane(viewer);
        scrollPane.setBorder(null);
        scrollPane.getViewport().setBackground(new Color(41, 49, 52));

        this.add(scrollPane, BorderLayout.CENTER);

        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
