
package SyntaxTree;

import generated.LenguajeParser;
import java.awt.BorderLayout;
import java.awt.Font;
import java.util.Arrays;
import javax.swing.JScrollPane;
import org.antlr.v4.gui.TreeViewer;
import org.antlr.v4.runtime.tree.ParseTree;
import PRUEBA.*;
/**
 *
 * @author carlos
 */
public class SyntaxTreePane extends javax.swing.JPanel {
    
    /**
     * Creates new form SyntaxTreePane
     */
    public SyntaxTreePane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private  void showTreeGui(LenguajeParser parser, ParseTree tree) {
    Font letra = new Font("Segoe UI", Font.BOLD, 10);

    // Limpiar el panel
    this.removeAll();
    this.setLayout(new BorderLayout());

    // Crear el TreeViewer
    TreeViewer viewer = new TreeViewer(
            Arrays.asList(parser.getRuleNames()),
            tree
    );

    viewer.setScale(1.2);     // ajustable
    viewer.setFont(letra);

    // Scroll para evitar recortes
    JScrollPane scrollPane = new JScrollPane(viewer);
    scrollPane.setBorder(null);

    // Agregar al JPanel Form
    this.add(scrollPane, BorderLayout.CENTER);

    // Refrescar la UI
    this.revalidate();
    this.repaint();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
