/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainFrame;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import org.fife.ui.rsyntaxtextarea.*;
import org.fife.ui.rsyntaxtextarea.templates.CodeTemplate;
import org.fife.ui.rsyntaxtextarea.templates.StaticCodeTemplate;
import org.fife.ui.rtextarea.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Insets;
import javax.swing.UIManager;

/**
 *
 * @author DFSS
 */
public class mainOld extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainOld.class.getName());
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea textArea = new RSyntaxTextArea();

    /**
     * Creates new form main
     */
    public mainOld() {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf()); 
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        UIManager.put("Button.arc", 16);          // roundness
        UIManager.put ("Component.arc", 16);
        UIManager.put("TextComponent.arc", 12);
        UIManager.put("ScrollBar.thumbArc", 999);
        UIManager.put("ScrollBar.thumbInsets", new Insets(2, 2, 2, 2));
        initComponents();
        //setFont(textArea, new Font("Comic Sans MS", Font.PLAIN, 16));

        

        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        textArea.setCodeFoldingEnabled(true);
        textArea.setAntiAliasingEnabled(true);
        textArea.setBracketMatchingEnabled(true);
        textArea.setHighlightCurrentLine(true);
        
        textArea.setTabsEmulated(true);
        textArea.setTabSize(4);

        RTextScrollPane sp = new RTextScrollPane(textArea);
        sp.setLineNumbersEnabled(true);
        jScrollPane1.setViewportView(sp);
        
      try {
         Theme theme = Theme.load(getClass().getResourceAsStream(
               "/mainFrame/dark2.xml"));
         theme.apply(textArea);
      } catch (IOException ioe) { // Never happens
         ioe.printStackTrace();
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelNombres = new javax.swing.JPanel();
        nombreDiego = new javax.swing.JLabel();
        nombreCarlos = new javax.swing.JLabel();
        nombreMiguel = new javax.swing.JLabel();
        nombrePedro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelEditor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTextArea textArea = new RSyntaxTextArea();
        panelBtn = new javax.swing.JPanel();
        btnSubir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelTitulo.setText("ANALIZADOR LÉXICO Y SINTÁCTICO");
        panelTitulo.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 420, 90));

        panelNombres.setMaximumSize(new java.awt.Dimension(415, 28));
        panelNombres.setMinimumSize(new java.awt.Dimension(415, 28));
        panelNombres.setPreferredSize(new java.awt.Dimension(415, 28));
        panelNombres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreDiego.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        nombreDiego.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreDiego.setText("DIEGO FERNANDO SANTIZO SAMAYOA");
        nombreDiego.setMaximumSize(new java.awt.Dimension(220, 15));
        nombreDiego.setMinimumSize(new java.awt.Dimension(220, 15));
        nombreDiego.setPreferredSize(new java.awt.Dimension(220, 15));
        panelNombres.add(nombreDiego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        nombreCarlos.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        nombreCarlos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreCarlos.setText("CARLOS ANDRÉS ARRIAZA LARA");
        nombreCarlos.setMaximumSize(new java.awt.Dimension(220, 15));
        nombreCarlos.setMinimumSize(new java.awt.Dimension(220, 15));
        nombreCarlos.setPreferredSize(new java.awt.Dimension(220, 15));
        panelNombres.add(nombreCarlos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, -1));

        nombreMiguel.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        nombreMiguel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreMiguel.setText("MIGUEL DAVID CONTRERAS JACINTO");
        nombreMiguel.setMaximumSize(new java.awt.Dimension(220, 15));
        nombreMiguel.setMinimumSize(new java.awt.Dimension(220, 15));
        nombreMiguel.setPreferredSize(new java.awt.Dimension(220, 15));
        panelNombres.add(nombreMiguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, -1));

        nombrePedro.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        nombrePedro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombrePedro.setText("PEDRO JOSÉ GÓMEZ VILLALOBOS");
        nombrePedro.setMaximumSize(new java.awt.Dimension(220, 15));
        nombrePedro.setMinimumSize(new java.awt.Dimension(220, 15));
        nombrePedro.setPreferredSize(new java.awt.Dimension(220, 15));
        panelNombres.add(nombrePedro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel1.setText("0901-22-15950");
        panelNombres.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel2.setText("0901-23-13862");
        panelNombres.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel3.setText("0901-22-3878");
        panelNombres.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setText("0901-23-4868");
        panelNombres.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));
        panelNombres.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 11, -1, -1));

        panelTitulo.add(panelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 340, 89));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        getContentPane().add(panelTitulo, gridBagConstraints);

        panelEditor.setMinimumSize(new java.awt.Dimension(584, 250));
        panelEditor.setPreferredSize(new java.awt.Dimension(584, 250));
        panelEditor.setLayout(new java.awt.GridBagLayout());

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setMaximumSize(new java.awt.Dimension(250, 150));
        textArea.setMinimumSize(new java.awt.Dimension(250, 150));
        textArea.setPreferredSize(new java.awt.Dimension(250, 150));
        jScrollPane1.setViewportView(textArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        panelEditor.add(jScrollPane1, gridBagConstraints);

        panelBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSubir.setText("SUBIR");
        btnSubir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBtn.add(btnSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        panelBtn.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 384;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelEditor.add(panelBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        getContentPane().add(panelEditor, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainOld().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel nombreCarlos;
    private javax.swing.JLabel nombreDiego;
    private javax.swing.JLabel nombreMiguel;
    private javax.swing.JLabel nombrePedro;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JPanel panelNombres;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
